name: ortho_measure_scanner
description: "A Flutter clinical scanning application for OrthoMeasure."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  http: ^1.2.0
  path_provider: ^2.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  google_mlkit_pose_detection: ^0.15.0
  opencv_dart: ^2.2.1+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
