/**
 * stlExporter.ts
 * 
 * Procedural binary STL generator for OrthoMeasure cast files.
 * 
 * Given cast geometry derived from real patient measurements, this module
 * generates a valid binary STL mesh that can be loaded directly in any
 * 3D slicer (Ultimaker Cura, PrusaSlicer, Bambu Studio, etc.) and
 * sent to a 3D printer.
 *
 * The geometry matches the Cast3DVisualizer canvas exactly:
 *   - Tapered cylinder (radiusProximal at top → radiusDistal at bottom)
 *   - Configurable wall thickness
 *   - Outer shell + inner shell + top/bottom rim caps
 *
 * Binary STL format:
 *   80-byte header | uint32 triangle count | N × (normal[3] + v0[3] + v1[3] + v2[3] + uint16 attr)
 *   Each float = 4 bytes (little-endian), each triangle = 50 bytes.
 */

export interface CastGeometry {
  /** Outer radius at the proximal (elbow/knee) end in mm */
  radiusProximal: number
  /** Outer radius at the distal (wrist/ankle) end in mm */
  radiusDistal: number
  /** Total cast height in mm */
  height: number
  /** Wall thickness in mm */
  thickness: number
  /** Number of vertical ring sections (more = smoother) */
  rings?: number
  /** Number of circumferential segments (more = smoother) */
  segments?: number
  /** Patient name for file header */
  patientName?: string
  /** Body part label */
  bodyPart?: string
}

interface Vec3 {
  x: number; y: number; z: number
}

function normalize(v: Vec3): Vec3 {
  const len = Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z) || 1
  return { x: v.x / len, y: v.y / len, z: v.z / len }
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return {
    x: a.y * b.z - a.z * b.y,
    y: a.z * b.x - a.x * b.z,
    z: a.x * b.y - a.y * b.x,
  }
}

function sub(a: Vec3, b: Vec3): Vec3 {
  return { x: a.x - b.x, y: a.y - b.y, z: a.z - b.z }
}

function triangleNormal(v0: Vec3, v1: Vec3, v2: Vec3): Vec3 {
  return normalize(cross(sub(v1, v0), sub(v2, v0)))
}

class STLWriter {
  private triangles: { normal: Vec3; v0: Vec3; v1: Vec3; v2: Vec3 }[] = []

  addTriangle(v0: Vec3, v1: Vec3, v2: Vec3) {
    const normal = triangleNormal(v0, v1, v2)
    this.triangles.push({ normal, v0, v1, v2 })
  }

  addQuad(v0: Vec3, v1: Vec3, v2: Vec3, v3: Vec3) {
    // Split quad into 2 triangles (CCW winding for outward normals)
    this.addTriangle(v0, v1, v2)
    this.addTriangle(v0, v2, v3)
  }

  toArrayBuffer(header = 'OrthoMeasure Cast — generated by OrthoMeasure AI'): ArrayBuffer {
    const count = this.triangles.length
    // 80-byte header + 4-byte count + count * 50 bytes per triangle
    const buffer = new ArrayBuffer(80 + 4 + count * 50)
    const view = new DataView(buffer)

    // Header (80 bytes, ASCII padded with nulls)
    const enc = new TextEncoder()
    const headerBytes = enc.encode(header.substring(0, 80).padEnd(80, '\0'))
    for (let i = 0; i < 80; i++) {
      view.setUint8(i, headerBytes[i] ?? 0)
    }

    // Triangle count
    view.setUint32(80, count, true /* little-endian */)

    // Triangles
    let offset = 84
    for (const t of this.triangles) {
      // Normal (3 × float32)
      view.setFloat32(offset, t.normal.x, true); offset += 4
      view.setFloat32(offset, t.normal.y, true); offset += 4
      view.setFloat32(offset, t.normal.z, true); offset += 4
      // Vertex 0
      view.setFloat32(offset, t.v0.x, true); offset += 4
      view.setFloat32(offset, t.v0.y, true); offset += 4
      view.setFloat32(offset, t.v0.z, true); offset += 4
      // Vertex 1
      view.setFloat32(offset, t.v1.x, true); offset += 4
      view.setFloat32(offset, t.v1.y, true); offset += 4
      view.setFloat32(offset, t.v1.z, true); offset += 4
      // Vertex 2
      view.setFloat32(offset, t.v2.x, true); offset += 4
      view.setFloat32(offset, t.v2.y, true); offset += 4
      view.setFloat32(offset, t.v2.z, true); offset += 4
      // Attribute byte count (always 0)
      view.setUint16(offset, 0, true); offset += 2
    }

    return buffer
  }
}

/**
 * Derive cast geometry from real patient measurements.
 * Circumference → radius via C = 2πr.
 * Falls back to anatomical averages if a measurement is missing.
 */
export function deriveGeometryFromMeasurements(
  measurements: { key: string; value: number; manualValue?: number }[],
  bodyPart: string,
  thicknessMm: number
): CastGeometry {
  const get = (keyword: string, fallback: number) => {
    const m = measurements.find(x => x.key.toLowerCase().includes(keyword))
    if (!m) return fallback
    return (m.manualValue !== undefined && m.manualValue > 0) ? m.manualValue : m.value
  }

  const part = (bodyPart || 'Forearm').toLowerCase()

  // Body-part–specific fallbacks (anatomical averages in mm)
  let fallbackProxCirc = 230, fallbackDistCirc = 165, fallbackLength = 250
  if (part.includes('wrist'))   { fallbackProxCirc = 165; fallbackDistCirc = 160; fallbackLength = 120 }
  if (part.includes('ankle'))   { fallbackProxCirc = 260; fallbackDistCirc = 220; fallbackLength = 200 }
  if (part.includes('elbow'))   { fallbackProxCirc = 290; fallbackDistCirc = 230; fallbackLength = 140 }
  if (part.includes('hand'))    { fallbackProxCirc = 165; fallbackDistCirc = 195; fallbackLength = 180 }
  if (part.includes('foot'))    { fallbackProxCirc = 220; fallbackDistCirc = 240; fallbackLength = 220 }
  if (part.includes('knee'))    { fallbackProxCirc = 380; fallbackDistCirc = 310; fallbackLength = 250 }
  if (part.includes('shoulder')){ fallbackProxCirc = 350; fallbackDistCirc = 290; fallbackLength = 200 }

  // Read from measurements (stored in cm, convert to mm)
  const proxCircMm = get('proximal', fallbackProxCirc / 10) * 10
  const distCircMm = get('wrist circumference', fallbackDistCirc / 10) * 10
  const lengthMm   = get('total length', fallbackLength / 10) * 10

  const rProx = proxCircMm / (2 * Math.PI)
  const rDist = distCircMm / (2 * Math.PI)

  return {
    radiusProximal: Math.max(10, rProx),
    radiusDistal:   Math.max(8, rDist),
    height:         Math.max(60, lengthMm),
    thickness:      thicknessMm,
    rings:          20,
    segments:       32,
  }
}

/**
 * Generate a printable binary STL for an orthopaedic cast shell.
 *
 * The mesh consists of:
 *  1. Outer tapered cylinder
 *  2. Inner tapered cylinder (= outer - thickness)
 *  3. Top rim annulus cap
 *  4. Bottom rim annulus cap
 *
 * All faces have outward-facing normals (CCW winding when viewed from outside).
 */
export function generateCastSTL(
  geo: CastGeometry,
  patientName = 'Patient',
  bodyPart = 'Forearm'
): ArrayBuffer {
  const {
    radiusProximal: rProx,
    radiusDistal:   rDist,
    height:         H,
    thickness:      T,
    rings           = 30, // Higher rings for smoother bends
    segments        = 32,
  } = geo

  const writer = new STLWriter()
  const PI2 = Math.PI * 2
  const part = (bodyPart || 'Forearm').toLowerCase()

  // Helper to generate a coordinate slice with organic shaping
  const getSliceParams = (t: number) => {
    let cx = 0
    let cy = -H / 2 + t * H
    let cz = 0
    let rxScale = 1.0
    let rzScale = 1.0

    // Base radius interpolation
    let baseRad = rDist * (1 - t) + rProx * t

    if (part.includes('ankle') || part.includes('foot')) {
      // 1. ANKLE/FOOT (L-shape Boot)
      // Joint bend is around t = 0.4
      const bendT = 0.4
      if (t < bendT) {
        const factor = (bendT - t) / bendT // 0 at joint, 1 at toes (t=0)
        cz = factor * H * 0.45             // project toes forward along +Z
        cy = -H / 2 + (bendT * H) * 0.15 * (1 - factor) // flatten sole
        rxScale = 1.0 - factor * 0.12      // narrower width
        rzScale = 1.0 + factor * 0.25      // elongated toes
        baseRad = rDist * 1.15             // foot is slightly bulkier
      } else {
        const factor = (t - bendT) / (1 - bendT)
        baseRad = rDist * (1 - factor) + rProx * factor
      }
    } else if (part.includes('elbow') || part.includes('knee')) {
      // 2. ELBOW/KNEE (Bent Joint)
      // Bent at 40 degrees in the middle
      const bendT = 0.5
      const angle = 0.7 // ~40 degrees
      if (t > bendT) {
        const factor = (t - bendT) / (1 - bendT)
        const bendDist = factor * (H * 0.5)
        cz = -bendDist * Math.sin(angle)   // project upper section back
        cy = -H / 2 + bendT * H + bendDist * Math.cos(angle)
      }
      // Bulge at joint
      const jointBulge = Math.exp(-Math.pow(t - bendT, 2) * 50) * 0.15
      baseRad = baseRad * (1 + jointBulge)
    } else if (part.includes('wrist') || part.includes('hand')) {
      // 3. WRIST/HAND (Contoured flared splint)
      // Narrow wrist at t = 0.3, flaring hand at t = 0
      const wristT = 0.3
      if (t < wristT) {
        const factor = (wristT - t) / wristT
        baseRad = rDist * (1.0 + factor * 0.22)
        rxScale = 1.1 + factor * 0.2       // wider palm
        rzScale = 0.95 - factor * 0.1      // flattened palm
      } else {
        const factor = (t - wristT) / (1 - wristT)
        baseRad = rDist * (1.0 - factor * 0.05) + rProx * factor
        rxScale = 1.0 + (1 - factor) * 0.1 // oval wrist
        rzScale = 1.0 - (1 - factor) * 0.1
      }
    } else {
      // 4. FOREARM/ARM (Muscle contour bulge)
      // Natural muscular bulge at t = 0.65
      const bulge = Math.sin(t * Math.PI) * 0.15
      baseRad = baseRad * (1.0 + bulge)
      rxScale = 1.05
      rzScale = 0.95
    }

    return { cx, cy, cz, rx: baseRad * rxScale, rz: baseRad * rzScale }
  }

  // Point generation for outer shell
  const outerPt = (r: number, s: number): Vec3 => {
    const t = r / rings
    const { cx, cy, cz, rx, rz } = getSliceParams(t)
    const theta = (s / segments) * PI2
    return {
      x: cx + rx * Math.cos(theta),
      y: cy,
      z: cz + rz * Math.sin(theta)
    }
  }

  // Point generation for inner shell (offset inwards by wall thickness)
  const innerPt = (r: number, s: number): Vec3 => {
    const t = r / rings
    const { cx, cy, cz, rx, rz } = getSliceParams(t)
    const theta = (s / segments) * PI2
    // Deduct thickness safely
    const inRx = Math.max(4, rx - T)
    const inRz = Math.max(4, rz - T)
    return {
      x: cx + inRx * Math.cos(theta),
      y: cy,
      z: cz + inRz * Math.sin(theta)
    }
  }

  // 1. Outer shell quads
  for (let r = 0; r < rings; r++) {
    for (let s = 0; s < segments; s++) {
      const sn = (s + 1) % segments
      writer.addQuad(
        outerPt(r,   s),
        outerPt(r,   sn),
        outerPt(r+1, sn),
        outerPt(r+1, s)
      )
    }
  }

  // 2. Inner shell quads (reversed winding = inward normals)
  for (let r = 0; r < rings; r++) {
    for (let s = 0; s < segments; s++) {
      const sn = (s + 1) % segments
      writer.addQuad(
        innerPt(r+1, s),
        innerPt(r+1, sn),
        innerPt(r,   sn),
        innerPt(r,   s)
      )
    }
  }

  // 3. Bottom cap (distal end, r=0) — annulus ring
  for (let s = 0; s < segments; s++) {
    const sn = (s + 1) % segments
    writer.addTriangle(outerPt(0, s), innerPt(0, s),   innerPt(0, sn))
    writer.addTriangle(outerPt(0, s), innerPt(0, sn),  outerPt(0, sn))
  }

  // 4. Top cap (proximal end, r=rings) — annulus ring
  for (let s = 0; s < segments; s++) {
    const sn = (s + 1) % segments
    writer.addTriangle(outerPt(rings, sn), innerPt(rings, sn),  innerPt(rings, s))
    writer.addTriangle(outerPt(rings, sn), innerPt(rings, s),   outerPt(rings, s))
  }

  const header = `OrthoMeasure Cast | Patient: ${patientName} | Body: ${bodyPart} | R_prox:${rProx.toFixed(1)}mm R_dist:${rDist.toFixed(1)}mm H:${H.toFixed(0)}mm T:${T.toFixed(1)}mm`
  return writer.toArrayBuffer(header)
}

/**
 * Trigger a browser download of an STL ArrayBuffer.
 */
export function downloadSTL(buffer: ArrayBuffer, filename: string) {
  const blob = new Blob([buffer], { type: 'application/octet-stream' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.stl') ? filename : `${filename}.stl`
  document.body.appendChild(a)
  a.click()
  setTimeout(() => {
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, 200)
}
